name: Push Model to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Tên model trên Replicate (ví dụ: thanh24t/xushi_edu_llm)'
        required: true
        default: 'thanh24t/xushi_edu_llm'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          sudo chmod +x /usr/local/bin/cog

      - name: Push model to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          # Di chuyển vào thư mục chứa cấu hình
          cd replicate_model
          
          # Đẩy model lên (Cog sẽ tự động dùng REPLICATE_API_TOKEN)
          cog push r8.im/${{ github.event.inputs.model_name }}
