name: Push Model to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Tên model trên Replicate (ví dụ: thanh24t/xushi_edu_llm)'
        required: true
        default: 'thanh24t/xushi_edu_llm'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push model to Replicate
        run: |
          cd replicate_model
          cog push r8.im/${{ github.event.inputs.model_name }}
